version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: car_fleet_db
    environment:
      POSTGRES_DB: car_fleet
      POSTGRES_USER: car_fleet_user
      POSTGRES_PASSWORD: edfCorsica
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Optional: Add a database admin interface
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  postgres_data:
